### PR TITLE
Adding Control-Plane Metrics for kubeburner

### PR DESCRIPTION
**Pull request by jtaleric**
### Description

Sharing example for control-plane things

### CODE REVIEW

**Review by sjug — APPROVED** [review]
/lgtm

Minimal example, do we want to document it anywhere?

**Review by Harshith-umesh — APPROVED** [review]
LGTM

**Comment by jtaleric** [comment]
> /lgtm
> 
> Minimal example, do we want to document it anywhere?

We don't have a minimal example, but hat isn't a bad idea.

**Comment by sjug** [comment]
Doubleplus good

**Pull request merged**
