### PR TITLE
fixed existing linter issues

### PR DESCRIPTION
**Pull request by amitsagtani97**
removed the extra commas from mb.py to
fix the code style errors.

### CODE REVIEW

**Comment by mohit-sheth** [comment]
LGTM, trailing commas help git diffs to be cleaner. 
Don't know how to turn it off in flake8
maybe next time

**Comment by amitsagtani97** [comment]
> LGTM, trailing commas help git diffs to be cleaner.
> Don't know how to turn it off in flake8
> maybe next time

@mohit-sheth we can add error code E231 in https://github.com/cloud-bulldozer/benchmark-comparison/blob/master/tox.ini#L22 for ignoring these errors, but not sure if it is ok to ignore these errors.

**Comment by amitsagtani97** [comment]
@mohit-sheth another solution is to add a space after the comma to ignore this issue, if you think these commas are required, I can add the extra space and add these commas back.

**Comment by mohit-sheth** [comment]
anything is fine with me!

**Comment by mohit-sheth** [comment]
LGTM

**Pull request merged**
