### PR TITLE
add storage csi touchstone config

### PR DESCRIPTION
**Pull request by liqcui**
### Description
Add storage csi touchstone config for CSI migration script, this need to be merged before PR https://github.com/openshift/svt/pull/757

### CODE REVIEW

**Comment by liqcui** [comment]
/cc @jtaleric 
@jtaleric Could you please help to review my PR when you are available, thanks!

**Comment by liqcui** [comment]
@jtaleric Thank you for your review my PR, do you how to fix below error?
or how to re-run the test? 
An unexpected error has occurred: CalledProcessError: command: ('/usr/bin/git', 'fetch', 'origin', '--tags')
return code: 128
stdout: (none)
stderr:
    fatal: could not read Username for 'https://gitlab.com/': No such device or address
Check the log at /home/runner/.cache/pre-commit/pre-commit.log
Error: The process '/opt/hostedtoolcache/Python/3.8.16/x64/bin/pre-commit' failed with exit code 3

**Comment by rsevilla87** [comment]
> @jtaleric Thank you for your review my PR, do you how to fix below error? or how to re-run the test? An unexpected error has occurred: CalledProcessError: command: ('/usr/bin/git', 'fetch', 'origin', '--tags') return code: 128 stdout: (none) stderr: fatal: could not read Username for 'https://gitlab.com/': No such device or address Check the log at /home/runner/.cache/pre-commit/pre-commit.log Error: The process '/opt/hostedtoolcache/Python/3.8.16/x64/bin/pre-commit' failed with exit code 3

Hey!, ci tests are not relevant here since this is just a new config addition and not a code change. I assume you've tested the configuration file

**Comment by liqcui** [comment]
> > @jtaleric Thank you for your review my PR, do you how to fix below error? or how to re-run the test? An unexpected error has occurred: CalledProcessError: command: ('/usr/bin/git', 'fetch', 'origin', '--tags') return code: 128 stdout: (none) stderr: fatal: could not read Username for 'https://gitlab.com/': No such device or address Check the log at /home/runner/.cache/pre-commit/pre-commit.log Error: The process '/opt/hostedtoolcache/Python/3.8.16/x64/bin/pre-commit' failed with exit code 3
> 
> Hey!, ci tests are not relevant here since this is just a new config addition and not a code change. I assume you've tested the configuration file so we can merge this patch.

Yes,  the configuration file has been tested, thanks!

**Review by rsevilla87 — APPROVED** [review]
lgtm

**Pull request merged**
