### PR TITLE
Add gen_averages.py script

### PR DESCRIPTION
**Pull request by dry923**
Add a python script that takes a json output file generated from touchstone and generates the averages the data. This can then be pushed to elasticsearch.

An example invocation:
```
$ touchstone_compare uperf elasticsearch ripsaw -url my_es.server:9200 -u 70d8dd67-390d-5a41-8d5f-a5d27582a6fe a7dfb872-06bc-5e10-b878-eca5eb0b3683 -o json > metrics.json

$ python3 gen_averages.py -f metrics.json -s "my_es.server" -p 80 -i uperf-gold
```

If no elasticsearch information is given it prints the output to stdout

### CODE REVIEW

**Comment by dry923** [comment]
The workflow for getting a "gold" uuid for a specific test:

1) Generate a json file from touchstone which uses the UUID's that you would like to use as a baseline
2) Pass the generated json file, along with, a UUID (or one will be generated for you), ES server, ES port, and an index name to upload too. 
3) The script will generate the averages of the information in the provided json file and upload it to the index supplied. *NOTE* if you decide not to provide ES information (or do not supply all of it) then it will simply print the generated json to stdout

**Comment by mohit-sheth** [comment]
can we the default input as yaml and json as additional param.
this way we can tap in this code after https://github.com/cloud-bulldozer/e2e-benchmarking/blob/3db4f605f45ea5e0061e912523878b419769bbb2/workloads/network-perf/run_network_compare.sh#L45

**Comment by mohit-sheth** [comment]
instead of printing the dict can we have -o yaml as default and -o json as an extra option. we can use this as an input to https://github.com/cloud-bulldozer/e2e-benchmarking/blob/3db4f605f45ea5e0061e912523878b419769bbb2/workloads/network-perf/csv_gen.py#L34

**Comment by dry923** [comment]
@mohit-sheth Updated per your comments. It can now take either a yaml or json (it'll figure it out) and then output a yaml or json (defaulting to yaml). You can also pass it a --output-file option for it to write to that file in the selected format.

**Comment by jtaleric** [comment]
so old....

**Comment by jtaleric** [comment]
@dry923 @mohit-sheth is this still relevant?

**Comment by dry923** [comment]
> @dry923 @mohit-sheth is this still relevant?

@jtaleric at this point i'd say it's probably not needed. I honestly don't recall the need behind it anyway. @mohit-sheth you good if I close it?

**Comment by mohit-sheth** [comment]
@dry923 yes, go ahead!

**Pull request closed without merging**
